gridSite/gridApp/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from gridApp import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/gridApp/home', permanent=False)),
    url(r'^home$', views.displayWelcome, name='home'),
    url(r'^about$', views.displayAbout, name='about'),
    url(r'^event/(?P<event_id>\d+$)', views.displayEventVendors,
        name='eventVendors'),
    url(r'^event/all$', views.displayUpcomingEvents, name='eventsAll'),
    url(r'^vendor/(?P<vendor_id>\d+)$', views.displayVendorInfo,
        name='vendorEvents'),
    url(r'^vendor/all$', views.displayAllVendors, name='vendorsAll'),
]

gridSite/gridSite/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib.auth import views as authViews
from django.views.generic.base import RedirectView
from gridApp.admin import adminSite


def getAdminRoot():
    import django
    from os.path import dirname
    return dirname(django.__file__) + "/contrib/admin/static/admin"

# We abstract the 'adminRoot' creation
# into a method for clarity purposes
adminRoot = getAdminRoot()

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/gridApp/', permanent=False)),
    url(r'^gridApp$', RedirectView.as_view(url='/gridApp/', permanent=False)),
    url(r'^gridApp/', include('gridApp.urls', namespace='gridApp')),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=False)),
    url(r'^admin/', include(adminSite.urls)),
    url(r'^admin/password_reset/$', authViews.password_reset,
        {'template_name': 'gridSiteAdmin/passwordResetForm.html'},
        name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', authViews.password_reset_done,
        {'template_name': 'gridSiteAdmin/passwordResetDone.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        authViews.password_reset_confirm,
        {'template_name': 'gridSiteAdmin/passwordResetConfirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', authViews.password_reset_complete,
        {'template_name': 'gridSiteAdmin/passwordResetComplete.html'},
        name='password_reset_complete'),
] + static(r'^static/admin/(?P<path>.*)$', document_root=adminRoot) \
  + static(r'^static/(?P<path>.*)$', document_root='trollApp/static')

gridSite/gridApp/models.py
from django.db import models


class gridEvent(models.Model):
    event_name = models.CharField(max_length=1000)
    event_location = models.CharField(max_length=1000)
    start_date = models.DateTimeField()

    def __unicode__(self):
        return self.event_name

    __repr__ = __unicode__
    __bytes__ = __unicode__
    __str__ = __unicode__

    class Meta:
        verbose_name = "Grid Event"
        verbose_name_plural = "Grid Events"


class gridVendor(models.Model):
    vendor_name = models.CharField(max_length=1000)
    vendor_link = models.CharField(max_length=1000)
    vendor_img = models.CharField(max_length=1000)
    event_count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.vendor_name

    __repr__ = __unicode__
    __bytes__ = __unicode__
    __str__ = __unicode__

    class Meta:
        verbose_name = "Grid Vendor"
        verbose_name_plural = "Grid Vendors"


class gridEventVendor(models.Model):
    grid_event = models.ForeignKey(gridEvent)
    grid_vendor = models.ForeignKey(gridVendor)

    def __unicode__(self):
        return "{vendorName} for {eventName}".format(
                vendorName=self.grid_vendor.vendor_name,
                eventName=self.grid_event.event_name)

    __repr__ = __unicode__
    __bytes__ = __unicode__
    __str__ = __unicode__

    class Meta:
        verbose_name = "Grid Event Vendors"
        verbose_name_plural = "Grid Event Vendors"

gridSite/gridApp/views.py
from gridApp.vendorUtil import getVendorInfo, getVendorsForEvent, \
     getUpcomingEvents, getPastEvents
from gridApp.models import gridEvent, gridVendor, gridEventVendor
from django.shortcuts import render
from django.db.models import Min
from datetime import datetime
from pytz import timezone


def updateData(today):
    gridEvent.objects.all().delete()
    gridVendor.objects.all().delete()
    gridEventVendor.objects.all().delete()

    pastEvents = getPastEvents(today)
    vendorInfo = getVendorInfo()

    vendors = [vendorName for (vendorName, vendorImg,
                               vendorLink) in vendorInfo]
    pastEventCountDict = {vendorName: 0 for vendorName in vendors}

    for eventName, startDate, eventLocation, eventDescription in pastEvents:
        eventVendors = getVendorsForEvent(eventDescription, vendors)

        for eventVendor in eventVendors:
            pastEventCountDict[eventVendor] = pastEventCountDict.get(
                eventVendor, 0) + 1

    for (vendorName, vendorLink, vendorImg) in vendorInfo:
        grid_vendor = gridVendor(
            vendor_name=vendorName, vendor_link=vendorLink,
            vendor_img=vendorImg, event_count=pastEventCountDict[vendorName])
        grid_vendor.save()

    upcomingEvents = getUpcomingEvents(today)

    for (eventName, startDate, eventLocation,
         eventDescription) in upcomingEvents:
        upcomingGridEvent = gridEvent(
            event_name=eventName.replace(
                'Off the Grid: ', ''),
            event_location=eventLocation,
            start_date=startDate)
        upcomingGridEvent.save()
        eventVendors = getVendorsForEvent(eventDescription, vendors)

        for eventVendor in eventVendors:
            upcomingGridVendor = gridVendor.objects.filter(
                vendor_name=eventVendor)[0]

            upcomingGridEventVendor = gridEventVendor(
                grid_event=upcomingGridEvent,
                grid_vendor=upcomingGridVendor)
            upcomingGridEventVendor.save()


def needToUpdate(today):
    return gridEventVendor.objects.count() == 0 or gridEvent.objects.aggregate(
        min_date=Min('start_date'))['min_date'] < today


def checkAndUpdate():
    today = datetime.now(tz=timezone('US/Pacific'))

    if needToUpdate(today):
        updateData(today)


def displayWelcome(request):
    return render(request, 'gridApp/welcomeDisplay.html')


def displayAbout(request):
    return render(request, 'gridApp/aboutDisplay.html')


def displayUpcomingEvents(request):
    checkAndUpdate()

    upcomingEvents = gridEvent.objects.order_by('start_date')
    context = {'upcomingEvents': upcomingEvents}

    return render(request, 'gridApp/eventAllDisplay.html', context)


def displayEventVendors(request, event_id):
    checkAndUpdate()

    grid_event = gridEvent.objects.get(pk=event_id)
    eventVendors = gridEventVendor.objects.filter(grid_event=grid_event)
    eventVendors = eventVendors.order_by('-grid_vendor__event_count')
    context = {'eventName': grid_event.event_name,
               'eventLocation': grid_event.event_location,
               'eventTime': grid_event.start_date,
               'eventVendors': eventVendors}

    return render(request, 'gridApp/eventVendorDisplay.html', context)


def displayVendorInfo(request, vendor_id):
    checkAndUpdate()

    eventVendor = gridVendor.objects.get(pk=vendor_id)
    context = {'vendorName': eventVendor.vendor_name,
               'vendorLink': eventVendor.vendor_link,
               'vendorImg': eventVendor.vendor_img,
               'vendorEventCount': eventVendor.event_count}

    return render(request, 'gridApp/vendorEventDisplay.html', context)


def displayAllVendors(request):
    checkAndUpdate()

    eventVendors = gridVendor.objects.order_by('-event_count')
    context = {'eventVendors': eventVendors}

    return render(request, 'gridApp/vendorAllDisplay.html', context)

gridSite/gridApp/templates/gridApp/aboutDisplay.html
{% include "gridApp/menuDisplay.html" %}

<title>OTGSF: About</title>

<h1 style="text-align:center">About Off the Grid SF Search</h1>
<p style="font-size:20px;line-height:200%">The purpose of this web application is to facilitate the searching of food
    trucks and vendors in<br>San Francisco. Inspired by an interview test for an internship, this application uses data
    from<br>Off the Grid SF <b>(OTGSF)</b> via the Facebook API to allow users to look up various trucks and<br>vendors, monitor
    their recent activity, and find events that they will be catering in the near future.<br>To learn more about Off the
    Grid SF, visit our Facebook page <a class="menuOption" href="https://www.facebook.com/OffTheGridSF" target="_blank">
        here</a> or our Twitter page <a class="menuOption" href="https://twitter.com/otgsf" target="_blank">here</a>.<br>
    Otherwise, we hope you enjoy using the website!</p>

gridSite/gridApp/templates/gridApp/eventAllDisplay.html
{% include "gridApp/menuDisplay.html" %}
{% load staticfiles %}

<title>OTGSF: Upcoming Events</title>

<h3>Upcoming Events</h3>
{% if upcomingEvents %}
	<p>Below is the list of upcoming events. If you want to learn more about an event, click the name.</p>
	<ol>
		{% for upcomingEvent in upcomingEvents %}
			<li><a href="{% url 'gridApp:eventVendors' upcomingEvent.id %}">
			{{ upcomingEvent.event_name }}</a></li>
		{% endfor %}
	</ol>
{% else %}
	<p>There are no upcoming events.</p>
{% endif %}

gridSite/gridApp/templates/gridApp/eventVendorDisplay.html
{% include "gridApp/menuDisplay.html" %}
{% load staticfiles %}

<title>OTGSF Event: {{ eventName }}</title>

<h3>Event Information: {{ eventName }}</h3>
<p><strong style="font-size:17px">Location: </strong>{{ eventLocation }}</p>
<p><strong style="font-size:17px">Start Time (in PST): </strong>{{ eventTime }}</p>

<h4>Participating Vendors</h4>
{% if eventVendors %}
	<p>To learn more about one of the participating vendors, click the name.</p>
	<ol>
		{% for eventVendor in eventVendors %}
			<li><a href="{% url 'gridApp:vendorEvents' eventVendor.grid_vendor.id %}">
			{{ eventVendor.grid_vendor.vendor_name }}</a></li>
		{% endfor %}
	</ol>
{% else %}
	<p>There are no vendors for this event.</p>
{% endif %}

gridSite/gridApp/templates/gridApp/menuDisplay.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, inital-scale=1" />
    <meta name="description" content="Website for all OTGSF Events" />
    <link rel="shortcut icon" href="/static/images/OTGSFlogo.ico" />
    <link rel="stylesheet" type="text/css" href="{%  static 'gridApp/style.css' %}" />
</head>
<body>
<h1 style="text-align:center">Off the Grid SF Search</h1>
<h2 style="text-align:center">Your Source for Food Trucks and Vendors in San Francisco</h2>

<div style="text-align:center">
<a class="menuOption" href="{% url 'gridApp:home' %}" style="padding-right:5em;">Home</a>
<a class="menuOption" href="{% url 'gridApp:about' %}" style="padding-right:5em;">About</a>
<a class="menuOption" href="{% url 'gridApp:eventsAll' %}" style="padding-right:5em;">Upcoming Events</a>
<a class="menuOption" href="{% url 'gridApp:vendorsAll' %}" style="padding-right:5em;">Available Trucks and Vendors</a>
<a class="menuOption" href="https://www.facebook.com/OffTheGridSF" style="padding-right:5em;" target="_blank">OTGSF Facebook Page</a>
<a class="menuOption" href="https://twitter.com/otgsf" target="_blank">Check Out OTGSF on Twitter!</a>
</div>

<hr>
</body>
</html>

gridSite/gridApp/templates/gridApp/vendorAllDisplay.html
{% include "gridApp/menuDisplay.html" %}
{% load staticfiles %}

<title>OTGSF: Vendors</title>

<h3>List of Current Vendors</h3>
{% if eventVendors %}
	<p>Below is the list of current vendors. The number of events next to each name is the number of events they<br>
	have catered in the past 30 days. If you want to learn more about a vendor or food truck, click the name.</p>
	<ol>
		{% for eventVendor in eventVendors %}
			<li><a href="{% url 'gridApp:vendorEvents' eventVendor.id %}">
			{{ eventVendor.vendor_name }} - {{ eventVendor.event_count }} event{{ eventVendor.event_count|pluralize }}</a></li>
		{% endfor %}
	</ol>
{% else %}
	<p>There are no vendors available at the moment.</p>
{% endif %}

gridSite/gridApp/templates/gridApp/vendorEventDisplay.html
{% include "gridApp/menuDisplay.html" %}

<title>OTGSF Vendor: {{ vendorName }}</title>

<h3>Vendor Information: {{ vendorName }}</h3>
<img src="{{ vendorImg }}"></img>
<p>Vendor Website: <a href='{{ vendorLink }}' target="_blank">{{ vendorLink }}</a></p>
<p>Number of events hosted in the past 30 days: {{ vendorEventCount }}</p>
<p>Interested in catering services from {{ vendorName }}? Click <a href="http://offthegridsf.com/catering", target="_blank">here</a>.</p>

gridSite/gridApp/templates/gridApp/welcomeDisplay.html
{% include "gridApp/menuDisplay.html" %}

<style>
    p {
        font-size: 20px;
    }
</style>

<title>OTGSF: Welcome!</title>

<h1 style="text-align:center">Welcome to the Off the Grid SF Search Homepage!</h1>
<p style="line-height:200%">Looking for information on San Francisco's fantastic food trucks and vendors?
    Then this is the<br> the <strong>perfect</strong> place to come and search! Here, you will find information
    on over <strong>200</strong> vendors, so feel<br>free to explore via one of the links below (or above)!</p><br>

<p><b>Interest about upcoming events?</b>
    Click <a class="menuOption" href="{% url 'gridApp:eventsAll' %}">here!</a></p>

<p><b>Want to know about the great food trucks and vendors around?</b>
    Click <a class="menuOption" href="{% url 'gridApp:vendorsAll' %}">here!</a></p>

gridSite/gridApp/templates/gridSiteAdmin/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="shortcut icon" href="/static/images/OTGSFlogo.ico" />
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

gridSite/gridApp/templates/gridSiteAdmin/base_site.html
{% extends "gridSiteAdmin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Django administration') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

gridSite/gridApp/templates/gridSiteAdmin/changeForm.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript">
        (function($) {
            $(document).ready(function() {
                $('.add-another').click(function(e) {
                    e.preventDefault();
                    var event = $.Event('django:add-another-related');
                    $(this).trigger(event);
                    if (!event.isDefaultPrevented()) {
                        showAddAnotherPopup(this);
                    }
                });
                $('.related-lookup').click(function(e) {
                    e.preventDefault();
                    var event = $.Event('django:lookup-related');
                    $(this).trigger(event);
                    if (!event.isDefaultPrevented()) {
                        showRelatedObjectLookupPopup(this);
                    }
                });
                $('body').on('click', '.related-widget-wrapper-link', function(e) {
                    e.preventDefault();
                    if (this.href) {
                        var event = $.Event('django:show-related', {href: this.href});
                        $(this).trigger(event);
                        if (!event.isDefaultPrevented()) {
                            showRelatedObjectPopup(this);
                        }
                    }
                });
                $('body').on('change', '.related-widget-wrapper select', function(e) {
                    var event = $.Event('django:update-related');
                    $(this).trigger(event);
                    if (!event.isDefaultPrevented()) {
                        updateRelatedObjectLinks(this);
                    }
                });
                $('.related-widget-wrapper select').trigger('change');

            {% if adminform and add %}
                $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
            {% endif %}
            });
        })(django.jQuery);
    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

gridSite/gridApp/templates/gridSiteAdmin/changeList.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_list %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
  {% endif %}
  {% if cl.formset or action_form %}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% if action_form %}{% if actions_on_top or actions_on_bottom %}
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
{% endif %}{% endif %}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ cl.opts.app_config.verbose_name }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}

{% block content %}
  <div id="content-main">
    {% block object-tools %}
      {% if has_add_permission %}
        <ul class="object-tools">
          {% block object-tools-items %}
            <li>
              {% url cl.opts|admin_urlname:'add' as add_url %}
              <a href="{% add_preserved_filters add_url is_popup to_field %}" class="addlink">
                {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
              </a>
            </li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}
    {% if cl.formset.errors %}
        <p class="errornote">
        {% if cl.formset.total_error_count == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% trans 'Filter' %}</h2>
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
{% endblock %}

gridSite/gridApp/templates/gridSiteAdmin/logout.html
{% extends "gridSiteAdmin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}